######################################################################
# Automatically generated by qmake (2.01a) Sun Sep 22 13:47:06 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
