######################################################################
# Automatically generated by qmake (2.01a) Thu May 23 21:04:24 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += FindDialog.h
SOURCES += FindDialog.cpp main.cpp

QMAKE_DISTCLEAN += make.out

