######################################################################
# Automatically generated by qmake (2.01a) Tue Nov 29 14:01:18 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += SimpleGUI.h
SOURCES += SimpleGUI.cpp
