######################################################################
# Automatically generated by qmake (2.01a) Wed Sep 18 03:54:01 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp

# Qt Libraries
# By default, QtCore and QtGui libs are linked into every Qt app.
# Because this is a commandline app, we do not need the GUI libs.
QT -= gui


