######################################################################
# Automatically generated by qmake (2.01a) Thu May 23 06:05:34 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp

QMAKE_DISTCLEAN += make.out

