######################################################################
# Automatically generated by qmake (2.01a) Thu May 23 05:45:06 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp

# I use make.out to allow me to instantly edit a quick list in Vim after compiling.
QMAKE_DISTCLEAN += make.out

