# m. # Run make and dump to make.out so can generate Vim quick list.
# a # Aliased to ./a so can run program w/o adding . to path.
# vq # If compile errors/warnings, opens them in a Vim quick list.
# :cn # Next quick list location.
a: main.cpp
	g++ main.cpp -o a

clean:
	rm -f a.exe
	rm -f a.out
	rm -f a
	rm -f *.o
	rm -f make.out
