######################################################################
# Automatically generated by qmake (2.01a) Tue Sep 17 21:51:36 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
