######################################################################
# Automatically generated by qmake (2.01a) Tue Nov 29 13:01:41 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += SlottedSignaller.h
SOURCES += SlottedSignaller.cpp
