######################################################################
# Automatically generated by qmake (2.01a) Mon Sep 23 19:03:51 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
