######################################################################
# Automatically generated by qmake (2.01a) Tue Nov 29 10:16:36 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += hello_Qt.cpp
