######################################################################
# Automatically generated by qmake (2.01a) Wed Sep 18 03:19:11 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
